config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :catagories do
    resources :products
  end
  resources :students

  resources :demos



get 'libraries', to: 'libraries#index', as: 'libraries'
get 'libraries/:id', to: 'libraries#show', as: 'library ' 
get 'libraries/new', to: 'libraries#new', as: 'new_library'
post 'libraries', to: 'library#create'



  

  #  get 'libraries/:id', to: 'libraries#show', as: 'library'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/catagory.rb
class Catagory < ApplicationRecord
end

app/models/demo.rb
class Demo < ApplicationRecord
end

app/models/product.rb
class Product < ApplicationRecord
    belongs_to :catagories
end

app/models/uniqueness.rb
class Uniqueness < ApplicationRecord
    validates :name, presence: false 
    validates :email, uniqueness: true
    validates :date, uniqueness: { scope: :month}, allow_nil: true
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/catagories_controller.rb
class CatagoriesController < ApplicationController
  before_action :set_catagory, only: %i[ show edit update destroy ]

  # GET /catagories or /catagories.json
  def index
    @catagories = Catagory.all
  end

  # GET /catagories/1 or /catagories/1.json
  def show
  end

  # GET /catagories/new
  def new
    @catagory = Catagory.new
  end

  # GET /catagories/1/edit
  def edit
  end

  # POST /catagories or /catagories.json
  def create
    @catagory = Catagory.new(catagory_params)

    respond_to do |format|
      if @catagory.save
        format.html { redirect_to catagory_url(@catagory), notice: "Catagory was successfully created." }
        format.json { render :show, status: :created, location: @catagory }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @catagory.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /catagories/1 or /catagories/1.json
  def update
    respond_to do |format|
      if @catagory.update(catagory_params)
        format.html { redirect_to catagory_url(@catagory), notice: "Catagory was successfully updated." }
        format.json { render :show, status: :ok, location: @catagory }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @catagory.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /catagories/1 or /catagories/1.json
  def destroy
    @catagory.destroy

    respond_to do |format|
      format.html { redirect_to catagories_url, notice: "Catagory was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_catagory
      @catagory = Catagory.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def catagory_params
      params.require(:catagory).permit(:name, :type)
    end
end

app/controllers/demos_controller.rb
class DemosController < ApplicationController
    def index
        @demos = Demo.all
    end

    def show
       
    end
end

app/controllers/libraries_controller.rb
class LibrariesController < ApplicationController
def index
  @libraries = Library.all
end

def show
  @library = Library.find(params[:id])
end

def new
end

def create 
end

end

app/controllers/member_controller.rb
class MemberController < ApplicationController
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: %i[ show edit update destroy ]

  # GET /products or /products.json
  def index
    @products = Product.all
  end

  # GET /products/1 or /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products or /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to product_url(@product), notice: "Product was successfully created." }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1 or /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to product_url(@product), notice: "Product was successfully updated." }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1 or /products/1.json
  def destroy
    @product.destroy

    respond_to do |format|
      format.html { redirect_to products_url, notice: "Product was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_params
      params.require(:product).permit(:name, :catagoroy, :price, :discount, :discount_type, :catagory_id)
    end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
    def index
        
      end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to user_url(@user), notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_url(@user), notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:name, :age, :number, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/catagories_helper.rb
module CatagoriesHelper
end

app/helpers/demos_helper.rb
module DemosHelper
end

app/helpers/library_helper.rb
module LibraryHelper
end

app/helpers/member_helper.rb
module MemberHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/catagories/_catagory.html.erb
<div id="<%= dom_id catagory %>">
  <p>
    <strong>Name:</strong>
    <%= catagory.name %>
  </p>

  <p>
    <strong>Type:</strong>
    <%= catagory.type %>
  </p>

</div>

app/views/catagories/_form.html.erb
<%= form_with(model: catagory) do |form| %>
  <% if catagory.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(catagory.errors.count, "error") %> prohibited this catagory from being saved:</h2>

      <ul>
        <% catagory.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>

    
  </div>

  <div>
    <%= form.label :type, style: "display: block" %>
    <%= form.text_field :type %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/catagories/edit.html.erb
<h1>Editing catagory</h1>

<%= render "form", catagory: @catagory %>

<br>

<div>
  <%= link_to "Show this catagory", @catagory %> |
  <%= link_to "Back to catagories", catagories_path %>
</div>

app/views/catagories/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Catagories</h1>

<div id="catagories">
  <% @catagories.each do |catagory| %>
    <%= render catagory %>
    <p>
      <%= link_to "Show this catagory", catagory %>
    </p>
  <% end %>
</div>

<%= link_to "New catagory", new_catagory_path %>

app/views/catagories/new.html.erb
<h1>New catagory</h1>

<%= render "form", catagory: @catagory %>

<br>

<div>
  <%= link_to "Back to catagories", catagories_path %>
</div>

app/views/catagories/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @catagory %>

<div>
  <%= link_to "Edit this catagory", edit_catagory_path(@catagory) %> |
  <%= link_to "Back to catagories", catagories_path %>

  <%= button_to "Destroy this catagory", @catagory, method: :delete %>
</div>

app/views/demos/_demos.html.erb
<div id="<%= dom_id demo %>">
  <p>
    <strong>Name:</strong>
    <%= demo.name %>
  </p>

  <p>
    <strong>Age:</strong>
    <%= demo.age %>
  </p>

  <p>
    <strong>city:</strong>
    <%= demo.city %>
  </p>

</div>

app/views/demos/_form.html.erb
<h1>New Name</h1>
<%= form_with(model: demo) do |form| %>

<div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :age, style: "display: block" %>
    <%= form.text_field :age %>
  </div>

  <div>
    <%= form.label :address, style: "display: block" %>
    <%= form.text_field :name %>

    <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/demos/index.html.erb
<h1>Listing</h1>


<div id="demos">
  <% @demos.each do |demo| %>
    <%= render demo %>
    <p>
      <%= link_to "Show this name", demo %>
    </p>
  <% end %>
</div>

<%= link_to new_demo_path  do %>
add name
  <%end%>

app/views/demos/new.html.erb
<%= render "form", demo: @demo %>




<div>
  <%= link_to "Back to listing", demos_path %>
</div>

app/views/demos/show.html.erb
<%= render @demo %>




<div>
  <%= link_to "Back to listing", demos_path %>

  <%= button_to "Destroy this name", @demo, method: :delete %>
</div>

app/views/libraries/_form.html.erb
<div>Listing</h1>
<%= form_with(model: library) do |form| %>

<div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :age, style: "display: block" %>
    <%= form.text_field :age %>
  </div>

  <div>
    <%= form.label :address, style: "display: block" %>
    <%= form.text_field :name %>

    <div>
    <%= form.submit %>
  </div>
<% end %>
  </div>

app/views/libraries/index.html.erb
<h1>Listing</h1>

<% @libraries.each do |library| %>
   <h3><%= library.titel %></h3>
   <p><%= library.discription %> </p>
   <% end  %>

app/views/libraries/new.html.erb
<h1>new list</h1>

app/views/libraries/show.html.erb
<h1>Listing</h1>

   <h3><%= @library.titel %></h3>
   <p><%= @ library.discription %> </p>

app/views/member/index.html.erb
<h1>Student data</h1>
 <div>
    <table border= '2' style ="text-align :center">
      <tr>
       <th >Student name</th>
        <th >Roll no</th>
        <th >maths</th>
        <th >science</th>
        <th >social sic.</th>
        <th >Total</th>
        <th >Percentage</th>
        <th >Remove</th>
      </tr>
<%= form_with model: @student do |form| %>
      <tr>
        <td>Nishant chauhan</td>
        <td>1</td>
        <td><%=form.number_field :mathes, in: 1.0..100.0, step: 1%></td>
        <td><%=form.number_field :science, in: 1.0..100.0, step: 1%></td>
        <td><%=form.number_field :scirnce, in: 1.0..100.0, step: 1%></td>
        <td><%=form.number_field :total %></td>
        <td>60%</td>
        <td><a href="#">Remove</a></td>
      </tr>

      <tr>
        <td>Madhav shrivastav</td>
        <td>2</td>
        <td><%=form.number_field :mathes, in: 1.0..100.0, step: 1%></td>
        <td><%=form.number_field :science, in: 1.0..100.0, step: 1%></td>
        <td><%=form.number_field :scirnce, in: 1.0..100.0, step: 1%></td>
        <td><%=form.number_field :total %></td>
        <td>60%</td>
        <td><a href="#">Remove</a></td>
      </tr>
      <% end %>
    </table>
 </div>

  <div>
    <table border= '2' style ="text-align :center">
      <tr>
        <th>Total student</th>
        <th>Highest mark</th>
        <th>Lowest mark</th>
        <th>Avarage mark</th>
      </tr>
      <tr>
        <td>0</td>
        <td>0</td>
        <td>0</td>
        <td>0</td>
      </tr>
    </table>
  </div>


<%= link_to "New student", new_student_path %>

app/views/member/new.html.erb
<h2>New Student</h2>


<%= render "form", student: @student %>



<%=link_to "New Studets" students_path %>

app/views/products/_form.html.erb
<%= form_with(model: product) do |form| %>
  <% if product.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
        <% product.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :catagoroy, style: "display: block" %>
    <%= form.text_field :catagoroy %>
  </div>

  <div>
    <%= form.label :price, style: "display: block" %>
    <%= form.number_field :price %>
  </div>

  <div>
    <%= form.label :discount, style: "display: block" %>
    <%= form.text_field :discount %>
  </div>

  <div>
    <%= form.label :discount_type, style: "display: block" %>
    <%= form.text_field :discount_type %>
  </div>

  <div>
    <%= form.label :catagory_id, style: "display: block" %>
    <%= form.text_field :catagory_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/products/_product.html.erb
<div id="<%= dom_id product %>">
  <p>
    <strong>Name:</strong>
    <%= product.name %>
  </p>

  <p>
    <strong>Catagoroy:</strong>
    <%= product.catagoroy %>
  </p>

  <p>
    <strong>Price:</strong>
    <%= product.price %>
  </p>

  <p>
    <strong>Discount:</strong>
    <%= product.discount %>
  </p>

  <p>
    <strong>Discount type:</strong>
    <%= product.discount_type %>
  </p>

  <p>
    <strong>Catagory:</strong>
    <%= product.catagory_id %>
  </p>

</div>

app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render "form", product: @product %>

<br>

<div>
  <%= link_to "Show this product", @product %> |
  <%= link_to "Back to products", products_path %>
</div>

app/views/products/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Products</h1>

<div id="products">
  <% @products.each do |product| %>
    <%= render product %>
    <p>
      <%= link_to "Show this product", product %>
    </p>
  <% end %>
</div>

<%= link_to "New product", new_product_path %>

app/views/products/new.html.erb
<h1>New product</h1>

<%= render "form", product: @product %>

<br>

<div>
  <%= link_to "Back to products", products_path %>
</div>

app/views/products/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @product %>

<div>
  <%= link_to "Edit this product", edit_product_path(@product) %> |
  <%= link_to "Back to products", products_path %>

  <%= button_to "Destroy this product", @product, method: :delete %>
</div>

app/views/students/_form.html.erb
<h2>New Student</h2>

app/views/students/index.html.erb
<h1>Student data</h1>
 <div>
    <table border= '2' style ="text-align :center">
      <tr>
       <th >Student name</th>
        <th >Roll no</th>
        <th >maths</th>
        <th >science</th>
        <th >social sic.</th>
        <th >Total</th>
        <th >Percentage</th>
        <th >Remove</th>
      </tr>
<%= form_with model: @student do |form| %>
      <tr>
        <td>Nishant chauhan</td>
        <td>1</td>
        <td><%=form.number_field :mathes, in: 1.0..100.0, step: 1%></td>
        <td><%=form.number_field :science, in: 1.0..100.0, step: 1%></td>
        <td><%=form.number_field :scirnce, in: 1.0..100.0, step: 1%></td>
        <td>180</td>
        <td>60%</td>
        <td><a href="#">Remove</a></td>
      </tr>

      <tr>
        <td>Madhav shrivastav</td>
        <td>2</td>
        <td><%=form.number_field :mathes, in: 1.0..100.0, step: 1%></td>
        <td><%=form.number_field :science, in: 1.0..100.0, step: 1%></td>
        <td><%=form.number_field :scirnce, in: 1.0..100.0, step: 1%></td>
        <td>180</td>
        <td>60%</td>
        <td><a href="#">Remove</a></td>
      </tr>
      <% end %>
    </table>
 </div>

  <div>
    <table border= '2' style ="text-align :center">
      <tr>
        <th>Total student</th>
        <th>Highest mark</th>
        <th>Lowest mark</th>
        <th>Avarage mark</th>
      </tr>
      <tr>
        <td>0</td>
        <td>0</td>
        <td>0</td>
        <td>0</td>
      </tr>
    </table>
  </div>

app/views/students/new.html.erb
<h2>New Student</h2>


<%= render "form", student: @student %>



<%=link_to "New Studets" students_path %>

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>

    <%= form.check_box :male %>
    <%= form.label :male, "male" %>
    <%= form.check_box :female %>
    <%= form.label :female, "female" %>
    <%= form.check_box :other %>
    <%= form.label :other, "other" %>
  </div>

  <div>
    <%= form.label :age, style: "display: block" %>
    <%= form.number_field :age %>

    <%= form.radio_button :age, "child" %>
    <%= form.label :age_child, "I am under 18" %>
    <%= form.radio_button :age, "adult" %>
    <%= form.label :age_adult, "I am over 18" %>
  </div>

  <div>
    <%= form.label :Date_of_birth, style: "display: block" %>
    <%= form.date_field :birth_date %>
  </div>

  <div>
    <%= form.label :number, style: "display: block" %>
    <%= form.telephone_field :number %> 
  </div>

  <div>
    <%= form.label :image, style: "display: block" %>
    <%= form.text_field :image %>
  </div>

  <div>
    <%= form.label :address, style: "display: block"%>
    <%= form.text_area :message, size: "70x5" %>
  <div>
    <%= form.label :city_and_state,  style: "color:DodgerBlue"%>
    <select name="city_id" id="city_id">
      <option value="3">bhavnagar</option>
      <option value="1">surat</option>
      <option value="2">baroda</option>
      <option value="4">ahemdabad</option>
      <option value="5">mumbai</option>
    </select>
  </div>

  <div>
    <%= form.label :add_image_file, style: "display: block;color:DodgerBlue"%>
    <%= form.file_field :picture %>
  </div>


  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/users/_user.html.erb
<div id="<%= dom_id user %>">
  <p>
    <strong>Name:</strong>
    <%= user.name %>
  </p>

  <p>
    <strong>Age:</strong>
    <%= user.age %>
  </p>

  <p>
    <strong>Number:</strong>
    <%= user.number %>
  </p>

  <p>
    <strong>Image:</strong>
    <%= user.image %>
  </p>

</div>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Show this user", @user %> |
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Users</h1>

<div id="users">
  <% @users.each do |user| %>
    <%= render user %>
    <p>
      <%= link_to "Show this user", user %>
    </p>
  <% end %>
</div>

<%= link_to "New user", new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @user %>

<div>
  <%= link_to "Edit this user", edit_user_path(@user) %> |
  <%= link_to "Back to users", users_path %>

  <%= button_to "Destroy this user", @user, method: :delete %>
</div>